# Discussed at https://travis-ci.community/t/python-support-on-windows/241/18
language: node_js            # this works for Linux but is an error on macOS or Windows
node_js:
  - 14

env:
  - CI=false

matrix:
  include:
    - name: "Linux"
      script:
        - cd client
        - yarn
        - yarn build
        - cd ../web
        - yarn
        - yarn build
        - cd ../electron
        - yarn
        - yarn build
        - yarn dist-linux
    - name: "MacOS"
      os: osx
      osx_image: xcode11  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      script:
        - brew install yarn
        - cd client
        - yarn
        - yarn build
        - cd ../web
        - yarn
        - yarn build
        - cd ../electron
        - yarn
        - yarn build
        - yarn dist-mac
    - name: "Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      script:
        - choco install yarn
        - cd client
        - yarn
        - yarn build
        - cd ../web
        - yarn
        - yarn build
        - cd ../electron
        - yarn
        - yarn build
        - yarn dist-windows

notifications:
  email: false
