const CONFIG_PATH = 'CONFIG'
export const CONFIG = {
  SET: `${CONFIG_PATH}_SET`,
  GET: `${CONFIG_PATH}_GET`
}

const BOARD_PATH = 'BOARD'
export const BOARD = {
  CREATE: `${BOARD_PATH}_CREATE`,
  READ: `${BOARD_PATH}_READ`,
  UPDATE: `${BOARD_PATH}_UPDATE`,
  DELETE: `${BOARD_PATH}_DELETE`
}

const BUTTON_PATH = 'BUTTON'
export const BUTTON = {
  CREATE: `${BUTTON_PATH}_CREATE`,
  READ: `${BUTTON_PATH}_READ`,
  READ_FOR_BOARD: `${BUTTON_PATH}_READ_FOR_BOARD`,
  UPDATE: `${BUTTON_PATH}_UPDATE`,
  DELETE: `${BUTTON_PATH}_DELETE`
}

const TRIGGER_PATH = 'TRIGGER'
export const TRIGGER = {
  CREATE: `${TRIGGER_PATH}_CREATE`,
  READ: `${TRIGGER_PATH}_READ`,
  UPDATE: `${TRIGGER_PATH}_UPDATE`,
  DELETE: `${TRIGGER_PATH}_DELETE`
}

const ACCOUNT_PATH = 'ACCOUNT'
export const ACCOUNT = {
  READ: `${ACCOUNT_PATH}_READ`,
  RELOAD: `${ACCOUNT_PATH}_RELOAD`,
  DELETE: `${ACCOUNT_PATH}_DELETE`,
  CONNECT: `${ACCOUNT_PATH}_CONNECT`
}

const TEMPLATE_PATH = 'TEMPLATE'
export const TEMPLATE = {
  CREATE: `${TEMPLATE_PATH}_CREATE`,
  READ: `${TEMPLATE_PATH}_READ`,
  UPDATE: `${TEMPLATE_PATH}_UPDATE`,
  DELETE: `${TEMPLATE_PATH}_DELETE`
}

const PLAYER_PATH = 'PLAYER'
export const PLAYER = {
  PLAY: `${PLAYER_PATH}_PLAY`,
  TTS: `${PLAYER_PATH}_TTS`,
}

const WORKSPACE_PATH = 'WORKSPACE'
export const WORKSPACE = {
  SET: `${WORKSPACE_PATH}_SET`,
  GET: `${WORKSPACE_PATH}_GET`,
}

const UTILS_PATH = 'UTILS'
export const UTILS = {
  SELECT_DIR: `${UTILS_PATH}_SELECT_DIR`,
  OPEN_ITEM: `${UTILS_PATH}_OPEN_ITEM`,
  LOCALE_GET: `${UTILS_PATH}_LOCALE_GET`
}

const OBS_PATH = 'OBS'
export const OBS = {
  GET: `${OBS_PATH}_GET`,
  SET: `${OBS_PATH}_SET`,
  RELOAD: `${OBS_PATH}_RELOAD`,
}

const WS_PATH = 'WS'
export const WS = {
  GET: `${WS_PATH}_GET`,
  SET: `${WS_PATH}_SET`
}
