export enum BOARD {
  CREATE = `BOARD_CREATE`,
  FIND_ALL = `BOARD_FIND_ALL`,
  FIND_ONE = `BOARD_FIND_ONE`,
  UPDATE = `BOARD_UPDATE`,
  DELETE = `BOARD_DELETE`,
}

export enum BUTTON {
  CREATE = `BUTTON_CREATE`,
  FIND_ALL = `BUTTON_FIND_ALL`,
  FIND_ONE = `BUTTON_FIND_ONE`,
  UPDATE = `BUTTON_UPDATE`,
  DELETE = `BUTTON_DELETE`,
}

export enum TRIGGER {
  CREATE = `TRIGGER_CREATE`,
  FIND_ALL = `TRIGGER_FIND_ALL`,
  FIND_ONE = `TRIGGER_FIND_ONE`,
  UPDATE = `TRIGGER_UPDATE`,
  DELETE = `TRIGGER_DELETE`,
}
