name: Build/release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build client
        run: |
          cd client
          yarn cache clean
          yarn install --network-timeout 1000000
          yarn build
        env:
          CI: false

      - name: Build web
        run: |
          cd web
          yarn cache clean
          yarn install --network-timeout 1000000
          yarn build
        env:
          CI: false

      - name: Copy client & web to electron
        run: |
          mkdir electron/build/
          cp -R web/build/ electron/build/web
          cp -R client/build/ electron/build/client

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          args: -c.snap.publish=github
          package_root: electron
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
