name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
      ls
      cd ./client
      ls
      yarn
      yarn build
      cd ../web
      yarn
      yarn build
      cd ../electron
      yarn
      yarn build
      yarn dist-linux


#  build-win:
#    runs-on: windows-latest
#
#    strategy:
#      matrix:
#        node-version: [12.x]
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - run: ls
#
#  build-mac:
#    runs-on: macos-latest
#
#    strategy:
#      matrix:
#        node-version: [12.x]
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - run: ls
